### ISSUE TITLE
Extended Angel's recipe revisions

### ISSUE THREAD

**Issue by Curry** [adamcirillo/ExtendedAngels#13]
In the most recent update to Angel's Bioprocessing, the tiering for the algae farm shifted, such that the T3 Algae farm now has the same tier requirements as the T4 algae farm in Extended angels:

https://github.com/Arch666Angel/mods/commit/ead07bec2f029ed89cd07e54972aa8cc1de73210#diff-1a9182b2da56317f04d372cc43ccda5afe17d296f3278dc99651aa647875bf0b

![image](https://user-images.githubusercontent.com/3466488/121816056-098a5a00-cc3f-11eb-89b5-a3584806c253.png)
![image](https://user-images.githubusercontent.com/3466488/121816061-0db67780-cc3f-11eb-8c8b-7709073d9322.png)

Should the Algae Farm 4 be moved to a higher tier/balanced around the new requirements?

**Comment by kirazy** [comment]
I've opened a branch to collect all recipe-related changes.

**Comment by KiwiHawk** [comment]
This change was reverted in Angel's. Algae farms are T0 - T3.

**Comment by kirazy** [comment]
Does your PR #20 account for the Algae farm tier reversion?

**Comment by kirazy** [comment]
Though I don't think the recipe changes ever got integrated.

**Comment by kirazy** [comment]
Ah it was integrated in 0.5.0. This issue should've been marked closed at that point, I think.

**Comment by KiwiHawk** [comment]
> Does your PR #20 account for the Algae farm tier reversion?

Yes, it does.
