### ISSUE TITLE
New Angel's Entities

### ISSUE THREAD

**Issue by KiwiHawk** [adamcirillo/ExtendedAngels#19]
https://github.com/Arch666Angel/mods/issues/805
https://github.com/Arch666Angel/mods/pull/853

New Angel's Refining entities:
- Filtration Unit 3
- Crystallizer 3

New Angel's Petrochem entities:
- Air Filter 3

### Required changes:
- Rename to Filtration unit 3 from Extended Angel's to Filtration unit 4
- Rename Crystallizer 3 from Extended Angel's to Crystallizer 4
- Remove Air Filter 3 from Extended Angel's

**Comment by kirazy** [comment]
Resolved by removing all entities in question. Whether to extend to a 4th tier of filtration unit/crystallizer or not will need to be evaluated.

**Comment by KiwiHawk** [comment]
> Resolved by removing all entities in question. Whether to extend to a 4th tier of filtration unit/crystallizer or not will need to be evaluated.

I think it should. The changes to Angel's do not increase the speed of the top tier Filtration Unit or Crystallizer. Instead, there is now a much smaller gap between the tiers.
