### ISSUE TITLE
No emission for buildings in 0.18

### ISSUE THREAD

**Issue by Lexanius** [adamcirillo/ExtendedAngels#5]
Hi,

I use your mod, but all new building have 0 pollution. So i visit the code and wiki and found that the building use maybe the wrong keyword. Instead of `emissions_per_second` or `emissions_per_minute` it is simple `emissions`. That's is what i have found:
https://wiki.factorio.com/Prototype/Entity#emissions_per_second
https://wiki.factorio.com/Types/EnergySource#emissions_per_minute

See prototypes/buildings/refining.lua:54
```
    energy_source =
    {
      type = "electric",
      usage_priority = "secondary-input",
      emissions = 0.03 / 3.5
    },
```

I hope it helps.

Lexanius

**Comment by adamcirillo** [comment]
this must of been something factorio changed I didn't know about. surprised the game didn't throw an error about it if it changed. I've fixed this in the next update that will be coming out now.
