### ISSUE TITLE
Bio building visuals and some bugs

### ISSUE THREAD

**Issue by danyax** [adamcirillo/ExtendedAngels#6]
Thank you very much for adding higher tires of bio buildings!

I have found some minor issues, here is the list

Tree Seed Generators (all of them) miss II and III overlay on items. Same for Arboretums. 

Seed Extractor does not have versions 2 and 3

Original Bio Refugium (Mk1) has speed 2. So versions Mk2 and Mk2 should have probably speed 3 and 4. Now they are at 1.25 and 2. There was a change some time ago in Angles, they upgraded Refugium speed from 0..75 to 2.

Would it be possible to add some tint or detail allowing to distinguish on map basic Warehouse and versions Mk2 - Mk4? Right now they look the same. You might get some inspiration from ShinyAngles mods by Zombee.

**Comment by adamcirillo** [comment]
I don't have permissions to edit angel's buildings only things like items and icons but I have fixed the speed and mk icons
