### ISSUE TITLE
Error loading mod

### ISSUE THREAD

**Issue by szentigrad3** [adamcirillo/ExtendedAngels#8]
trying to make compat with py and this happens https://i.imgur.com/Wnwy4sT.png

**Comment by adamcirillo** [comment]
I've removed bob's recipe and you must be looking for it. I've made my own version using angels machines you can find it as molten-copper-tungsten-smelting-1, copper-tungsten-smelting-1 & copper-tungsten-smelting-2. you would have to add a check in to do something different if you find my mod is installed.

**Comment by szentigrad3** [comment]
i'm not sure which mod is causing the problem

**Comment by adamcirillo** [comment]
well try disabling mods one by one till it goes away i know disabling mine will since its my mod removing the recipe
